using System.Text.Json;
using Elementalist.Infrastructure.DataAccess.CardData;

namespace ElementalistTests.Features.Card;

internal class MockCardRepository : ICardRepository
{
    private readonly List<Elementalist.Models.Card> _cards = [
        JsonSerializer.Deserialize<Elementalist.Models.Card>(pudgeJson, JsonSerializerOptions.Web)!,
        JsonSerializer.Deserialize<Elementalist.Models.Card>(DreamQuestJson, JsonSerializerOptions.Web)!,
        JsonSerializer.Deserialize<Elementalist.Models.Card>(HoundsJson, JsonSerializerOptions.Web)!,
        JsonSerializer.Deserialize<Elementalist.Models.Card>(WolpertingerJson, JsonSerializerOptions.Web)!,
        ];

    public Task<IEnumerable<Elementalist.Models.Card>> GetCards()
    {
        return Task.FromResult(_cards.AsEnumerable());
    }

    public Task<IEnumerable<Elementalist.Models.Card>> GetCardsMatching(Func<Elementalist.Models.Card, bool> predicate)
    {
        return Task.FromResult(_cards.Where(predicate));
    }

    const string pudgeJson = """{ "id": "cmt85yol700xrnwcyda0jt1sd", "name": "Pudge Butcher", "slug": "pudge_butcher", "engine": { "type": "Minion", "category": "Spell", "rarity": "Exceptional", "slot": "Exceptional", "rules": "Immobile\r\n\r\nTap → Shoot a projectile. If it hits a unit, drag it to this location. Pudge may fight it when it arrives.", "cost": 4, "attack": 5, "defense": 5, "life": null, "air": 0, "earth": 2, "fire": 0, "water": 0, "elements": [ "Earth" ], "subtypes": [ "Demon" ], "keywords": [ "Immobile" ], "umbrellas": [ "Evil" ], "back": null }, "printings": [ { "id": "cmt86e2xf0814nwcyc4a10wv7", "slug": "999-pudge_butcher-d-s", "printedAt": "2024-05-10T07:00:00.000Z", "set": { "name": "Promo", "code": "999", "releasedAt": "2026-08-25T04:39:08.860Z" }, "meta": { "finish": "Standard", "product": "Dust", "typeline": "An Exceptional Demon of corpulent choler", "flavor": null, "artist": { "name": "Brian Smith", "slug": "brian_smith" }, "back": null } }, { "id": "cmt862rdg032enwcyxej0uu3d", "slug": "002-pudge_butcher-b-s", "printedAt": "2023-10-06T07:00:00.000Z", "set": { "name": "Beta", "code": "002", "releasedAt": "2026-08-25T04:29:12.082Z" }, "meta": { "finish": "Standard", "product": "Booster", "typeline": "An Exceptional Demon of corpulent choler", "flavor": null, "artist": { "name": "Brian Smith", "slug": "brian_smith" }, "back": null } }, { "id": "cmt862qi0031znwcyr5phq9u7", "slug": "002-pudge_butcher-b-f", "printedAt": "2023-10-06T07:00:00.000Z", "set": { "name": "Beta", "code": "002", "releasedAt": "2026-08-25T04:29:12.082Z" }, "meta": { "finish": "Foil", "product": "Booster", "typeline": "An Exceptional Demon of corpulent choler", "flavor": null, "artist": { "name": "Brian Smith", "slug": "brian_smith" }, "back": null } }, { "id": "cmt85ypxa00ygnwcywx3z8mv2", "slug": "001-pudge_butcher-b-s", "printedAt": "2023-06-22T07:00:00.000Z", "set": { "name": "Alpha", "code": "001", "releasedAt": "2026-08-25T04:21:27.405Z" }, "meta": { "finish": "Standard", "product": "Booster", "typeline": "An Exceptional Demon of corpulent choler", "flavor": null, "artist": { "name": "Brian Smith", "slug": "brian_smith" }, "back": null } }, { "id": "cmt85yp1900xznwcy5i2kdyat", "slug": "001-pudge_butcher-b-f", "printedAt": "2023-06-22T07:00:00.000Z", "set": { "name": "Alpha", "code": "001", "releasedAt": "2026-08-25T04:21:27.405Z" }, "meta": { "finish": "Foil", "product": "Booster", "typeline": "An Exceptional Demon of corpulent choler", "flavor": null, "artist": { "name": "Brian Smith", "slug": "brian_smith" }, "back": null } } ] }""";
    const string DreamQuestJson = """{ "id": "cmt85x90h0055nwcyqfofw5m0", "name": "Dream-Quest", "slug": "dream_quest", "engine": { "type": "Magic", "category": "Spell", "rarity": "Unique", "slot": "Unique", "rules": "An allied Spellcaster falls asleep and is disabled until hurt. At the start of your next turn, if it's still asleep, you may wake it up to search your spellbook for a card and put it into your hand. Shuffle if needed.", "cost": 1, "attack": null, "defense": null, "life": null, "air": 1, "earth": 0, "fire": 0, "water": 0, "elements": [ "Air" ], "subtypes": [], "keywords": [ "Disabled", "Spellcaster" ], "umbrellas": [], "back": null }, "printings": [ { "id": "cmt861atb02dbnwcyz26sntq0", "slug": "002-dream_quest-b-s", "printedAt": "2023-10-06T07:00:00.000Z", "set": { "name": "Beta", "code": "002", "releasedAt": "2026-08-25T04:29:12.082Z" }, "meta": { "finish": "Standard", "product": "Booster", "typeline": "Unique Magic glimpses beyond the veil", "flavor": null, "artist": { "name": "Elvira Shakirova", "slug": "elvira_shakirova" }, "back": null } }, { "id": "cmt8619xn02cxnwcyd9rwdk8m", "slug": "002-dream_quest-b-f", "printedAt": "2023-10-06T07:00:00.000Z", "set": { "name": "Beta", "code": "002", "releasedAt": "2026-08-25T04:29:12.082Z" }, "meta": { "finish": "Foil", "product": "Booster", "typeline": "Unique Magic glimpses beyond the veil", "flavor": null, "artist": { "name": "Elvira Shakirova", "slug": "elvira_shakirova" }, "back": null } }, { "id": "cmt85xac7005unwcylh5b6nth", "slug": "001-dream_quest-b-s", "printedAt": "2023-06-22T07:00:00.000Z", "set": { "name": "Alpha", "code": "001", "releasedAt": "2026-08-25T04:21:27.405Z" }, "meta": { "finish": "Standard", "product": "Booster", "typeline": "Unique Magic glimpses beyond the veil", "flavor": null, "artist": { "name": "Elvira Shakirova", "slug": "elvira_shakirova" }, "back": null } }, { "id": "cmt85x9gf005fnwcym307g2jf", "slug": "001-dream_quest-b-f", "printedAt": "2023-06-22T07:00:00.000Z", "set": { "name": "Alpha", "code": "001", "releasedAt": "2026-08-25T04:21:27.405Z" }, "meta": { "finish": "Foil", "product": "Booster", "typeline": "Unique Magic glimpses beyond the veil", "flavor": null, "artist": { "name": "Elvira Shakirova", "slug": "elvira_shakirova" }, "back": null } } ] }""";
    const string HoundsJson = """ { "id": "cmt85zezb01chnwcyup9getj4", "name": "Hounds of Ondaros", "slug": "hounds_of_ondaros", "engine": { "type": "Minion", "category": "Spell", "rarity": "Elite", "slot": "Elite", "rules": "Airborne, Burrowing, Submerge, Voidwalk\r\n\r\nNearby enemies permanently lose Stealth.", "cost": 5, "attack": 4, "defense": 4, "life": null, "air": 2, "earth": 0, "fire": 0, "water": 0, "elements": [ "Air" ], "subtypes": [ "Beast" ], "keywords": [ "Airborne", "Burrowing", "Stealth", "Submerge", "Voidwalk" ], "umbrellas": [], "back": null }, "printings": [ { "id": "cmt863dec03d0nwcyrhf6j5cd", "slug": "002-hounds_of_ondaros-b-s", "printedAt": "2023-10-06T07:00:00.000Z", "set": { "name": "Beta", "code": "002", "releasedAt": "2026-08-25T04:29:12.082Z" }, "meta": { "finish": "Standard", "product": "Booster", "typeline": "Nowhere is safe from these Elite Beasts", "flavor": null, "artist": { "name": "Francesca Baerald", "slug": "francesca_baerald" }, "back": null } }, { "id": "cmt863cig03clnwcy8njsyrnd", "slug": "002-hounds_of_ondaros-b-f", "printedAt": "2023-10-06T07:00:00.000Z", "set": { "name": "Beta", "code": "002", "releasedAt": "2026-08-25T04:29:12.082Z" }, "meta": { "finish": "Foil", "product": "Booster", "typeline": "Nowhere is safe from these Elite Beasts", "flavor": null, "artist": { "name": "Francesca Baerald", "slug": "francesca_baerald" }, "back": null } }, { "id": "cmt85zgap01d6nwcy654fia2t", "slug": "001-hounds_of_ondaros-b-s", "printedAt": "2023-06-22T07:00:00.000Z", "set": { "name": "Alpha", "code": "001", "releasedAt": "2026-08-25T04:21:27.405Z" }, "meta": { "finish": "Standard", "product": "Booster", "typeline": "Nowhere is safe from these Elite Beasts", "flavor": null, "artist": { "name": "Francesca Baerald", "slug": "francesca_baerald" }, "back": null } }, { "id": "cmt85zff301conwcyy5nhbh3s", "slug": "001-hounds_of_ondaros-b-f", "printedAt": "2023-06-22T07:00:00.000Z", "set": { "name": "Alpha", "code": "001", "releasedAt": "2026-08-25T04:21:27.405Z" }, "meta": { "finish": "Foil", "product": "Booster", "typeline": "Nowhere is safe from these Elite Beasts", "flavor": null, "artist": { "name": "Francesca Baerald", "slug": "francesca_baerald" }, "back": null } } ] }""";
    const string WolpertingerJson = """{ "id": "cmt865snk04kznwcycnzrua16", "name": "Wolpertinger", "slug": "wolpertinger", "engine": { "type": "Minion", "category": "Spell", "rarity": "Elite", "slot": "Elite", "rules": "Has +1 power for each of your dead Beasts.", "cost": 4, "attack": 0, "defense": 0, "life": null, "air": 0, "earth": 2, "fire": 0, "water": 0, "elements": [ "Earth" ], "subtypes": [ "Beast" ], "keywords": [], "umbrellas": [], "back": null }, "printings": [ { "id": "cmt865tyo04lnnwcy9ga37rhr", "slug": "004-wolpertinger-b-s", "printedAt": "2024-10-04T07:00:00.000Z", "set": { "name": "Arthurian Legends", "code": "004", "releasedAt": "2026-08-25T04:32:18.603Z" }, "meta": { "finish": "Standard", "product": "Booster", "typeline": "An Elite Beast of tooth, claw, and horn", "flavor": null, "artist": { "name": "Séverine Pineaux", "slug": "severine_pineaux" }, "back": null } }, { "id": "cmt865t3604l7nwcy1ydod5ny", "slug": "004-wolpertinger-b-f", "printedAt": "2024-10-04T07:00:00.000Z", "set": { "name": "Arthurian Legends", "code": "004", "releasedAt": "2026-08-25T04:32:18.603Z" }, "meta": { "finish": "Foil", "product": "Booster", "typeline": "An Elite Beast of tooth, claw, and horn", "flavor": null, "artist": { "name": "Séverine Pineaux", "slug": "severine_pineaux" }, "back": null } } ] }""";
}

