name: Trigger auto deployment for disco-bot-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/disco-bot-container-AutoDeployTrigger-0e9da29e-57bc-4d77-b8b0-14e28a3d90b8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DISCOBOTCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DISCOBOTCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DISCOBOTCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: elementalist.azurecr.io
          registryUsername: ${{ secrets.DISCOBOTCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DISCOBOTCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: disco-bot-container
          resourceGroup: DiscoBot-Resource-Group
          imageToBuild: elementalist.azurecr.io/disco-bot-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


